name: Generate and Push PDF from README

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      - name: Convert Markdown to PDF
        run: |
          pandoc README.md -o README.pdf --pdf-engine=wkhtmltopdf

      - name: Commit and Push the PDF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add README.pdf
          git commit -m "Generated README.pdf from README.md [skip ci]" || echo "No changes to commit"
          git push

