name: Generate and Push PDF from README

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Allows the workflow to commit the PDF back to the repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install md-to-pdf
      - name: Install md-to-pdf
        run: npm install -g md-to-pdf

      # Step 4: Convert Markdown to PDF (with --no-sandbox flag)
      - name: Convert README.md to PDF
        env:
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome"  # Use system Chromium, if needed
        run: |
          echo '{ "puppeteer": { "args": ["--no-sandbox"] } }' > md-to-pdf.config.json
          md-to-pdf README.md --config-file md-to-pdf.config.json

      # Step 5: Push the generated PDF to the repository
      - name: Commit and Push PDF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add README.pdf
          git commit -m "Generated README.pdf from README.md [skip ci]" || echo "No changes to commit"
          git push

