name: Generate and Push PDF from README

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Allows the workflow to commit the PDF back to the repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up LaTeX
      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-xetex

      # Step 3: Convert Markdown to PDF using LaTeX
      - name: Convert Markdown to PDF
        run: |
          pandoc README.md -o README.pdf --pdf-engine=xelatex

      # Step 4: Push the generated PDF to the repository
      - name: Commit and Push PDF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add README.pdf
          git commit -m "Generated README.pdf from README.md [skip ci]" || echo "No changes to commit"
          git push

